version: "3.9"
services:
  app:
    container_name: tickets_processor
    image: araujoyuri/tickets_processor
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    command: uvicorn tickets_processor.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    environment:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    container_name: tickets_processor-worker
    image: araujoyuri/tickets_processor-worker
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    command: celery -A worker.main.celery worker -l INFO -E
    volumes:
      - .:/app
    depends_on:
      - app
      - redis

  flower:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    command: sh -c "timeout 10 sleep 5 && celery -A worker.main.celery flower"
    volumes:
      - .:/app
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - worker
      - redis

  redis:
    image: redis
    container_name: redis
    command: redis-server
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
