version: "3.9"
services:
  app:
    container_name: tickets_processor
    image: araujoyuri/tickets_processor
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    command: uvicorn tickets_processor.main:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - .:/app
    environment:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - redis

  worker:
    container_name: tickets_processor-worker
    image: araujoyuri/tickets_processor-worker
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    command: celery -A worker.main.celery worker -P eventlet -l info -E
    volumes:
      - .:/app
    depends_on:
      - app
      - redis

  flower:
    container_name: tickets_processor-flower
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    command: sh -c "timeout 10 sleep 5 && celery -A worker.main.celery flower"
    volumes:
      - .:/app
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - worker
      - redis

  redis:
    image: redis
    container_name: redis
    command: redis-server
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: DUMMYIDEXAMPLE
      AWS_SECRET_ACCESS_KEY: DUMMYEXAMPLEKEY
    depends_on:
      - dynamodb-local

volumes:
  redis_data:
